version: "3.8"

services:
  nginx:
    build: ./nginx
    image: nginx
    container_name: "nginx_cont"
    ports:
      - "80:80"
    depends_on:
      - django_app
    networks:
      - notes-app-nw
    restart: always

  django_app:
    build:
      context: .
    image: django_app
    container_name: "django_cont"
    ports:
      - "8000:8000"
    env_file:
      - ".env"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - notes-app-nw
    restart: always
    command: >
      sh -c "python manage.py migrate &&
             gunicorn notesapp.wsgi:application --bind 0.0.0.0:8000"

  db:
    image: mysql:8.0
    container_name: "db"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test_db
    volumes:
      - ./data/mysql/db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot", "--silent"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

    networks:
      - notes-app-nw
    restart: always

networks:
  notes-app-nw:
